blank_issues_enabled: false
contact_links:
  - name: 💬 Questions and discussion
    url: https://github.com/durrante/Win32Forge/discussions
    about: Have a question rather than a bug? Please start a discussion here.
